CREATE TABLE IF NOT EXISTS urls (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name VARCHAR(255) NOT NULL UNIQUE,
created_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS url_checks (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
url_id INT REFERENCES urls(id) NOT NULL,
status_code SMALLINT NOT NULL,
h1 VARCHAR(255),
title VARCHAR(255),
description VARCHAR(255),
created_at TIMESTAMP DEFAULT NOW()
);